# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d3013bcbe8796bcaa46bce974cbf50dd473e2fb15ef818ea0550916f5b263a187cffa1d6d44ed3fb11523b96066158743876fbb02b19b07f1f97066f5b5f637

test:
  secret_key_base: 00bf4ed4a6441540392cfaf55469cf1959f42b161a68208c0623fe59dd482302550ad156754f66210937df54779fa36070c6069a94288bb993bf70a4fa2b9052

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
